import React, { useState, useEffect } from 'react';
import {
  MessageSquareText,
  Bot,
  Mail,
  Send,
  CheckCircle2,
  Clock,
  Filter,
  User,
  Phone,
  Sparkles,
  AlertCircle,
  ExternalLink,
  ChevronRight,
  ShieldCheck
} from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import adminService from '../../services/adminService';

const CHANNEL_FILTERS = ['All', 'AI Assistant', 'Contact Form', 'Direct Ticket'];
const STATUS_FILTERS = ['All', 'Pending Counselor', 'Resolved by AI', 'Replied'];

export default function AdminMessages() {
  const { isDark } = useTheme();

  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedMessage, setSelectedMessage] = useState(null);
  const [channelFilter, setChannelFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('All');
  const [replyText, setReplyText] = useState('');
  const [counselorName, setCounselorName] = useState('Dr. S. K. Patnaik');
  const [sending, setSending] = useState(false);
  const [replySuccess, setReplySuccess] = useState(false);

  const fetchMessages = async () => {
    try {
      setLoading(true);
      const data = await adminService.getMessages({
        channel: channelFilter,
        status: statusFilter
      });
      setMessages(data || []);
    } catch (err) {
      console.error('Failed to load messages:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMessages();
  }, [channelFilter, statusFilter]);

  const handleOpenReplyModal = (msg) => {
    setSelectedMessage(msg);
    setReplyText(msg.counselorReply || '');
    setReplySuccess(false);
  };

  const handleSendReply = async (e) => {
    e.preventDefault();
    if (!selectedMessage || !replyText.trim()) return;

    setSending(true);
    try {
      await adminService.replyToMessage(selectedMessage.id, replyText, counselorName);
      setReplySuccess(true);
      setTimeout(() => {
        setSelectedMessage(null);
        fetchMessages();
      }, 1500);
    } catch (err) {
      alert('Failed to send reply: ' + err.message);
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* ============================================================
          HEADER
      ============================================================ */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
            Student Inquiries & AI Conversation Logs
          </h1>
          <p className={`text-xs sm:text-sm mt-1 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>
            Audit transcripts generated by the 24/7 AI Admission Agent and respond directly to candidate tickets.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-300">
          <span>Inquiries Recorded: <strong>{messages.length}</strong></span>
        </div>
      </div>

      {/* ============================================================
          FILTER CONTROLS
      ============================================================ */}
      <div className={`p-4 rounded-2xl border flex flex-col md:flex-row items-center justify-between gap-4 ${
        isDark ? 'bg-slate-900/80 border-slate-800' : 'bg-white border-slate-200'
      }`}>
        {/* Channel Filters */}
        <div className="flex items-center gap-1.5 overflow-x-auto w-full md:w-auto">
          <span className="text-xs font-bold text-slate-400 mr-1">Channel:</span>
          {CHANNEL_FILTERS.map((ch) => (
            <button
              key={ch}
              onClick={() => setChannelFilter(ch)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                channelFilter === ch
                  ? 'bg-indigo-600 text-white shadow-sm'
                  : isDark
                    ? 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-200'
              }`}
            >
              {ch}
            </button>
          ))}
        </div>

        {/* Status Filters */}
        <div className="flex items-center gap-1.5 overflow-x-auto w-full md:w-auto">
          <span className="text-xs font-bold text-slate-400 mr-1">Status:</span>
          {STATUS_FILTERS.map((st) => (
            <button
              key={st}
              onClick={() => setStatusFilter(st)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                statusFilter === st
                  ? 'bg-brand-600 text-white shadow-sm'
                  : isDark
                    ? 'bg-slate-950 text-slate-400 hover:text-white border border-slate-800'
                    : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-200'
              }`}
            >
              {st}
            </button>
          ))}
        </div>
      </div>

      {/* ============================================================
          MESSAGES LIST
      ============================================================ */}
      <div className="space-y-4">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`p-5 rounded-2xl border transition-all hover:border-indigo-500/50 ${
              isDark ? 'bg-slate-900/90 border-slate-800' : 'bg-white border-slate-200'
            }`}
          >
            <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 pb-3 border-b border-slate-800/80 mb-3">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-400">
                  {msg.channel === 'AI Assistant' ? <Bot className="w-5 h-5" /> : <Mail className="w-5 h-5" />}
                </div>
                <div>
                  <h3 className="font-bold text-sm text-white flex items-center gap-2">
                    {msg.studentName}
                    <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-slate-800 text-slate-300">
                      {msg.channel}
                    </span>
                    {msg.priority === 'Urgent' && (
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/30">
                        Urgent
                      </span>
                    )}
                  </h3>
                  <p className="text-xs text-slate-400">{msg.email} · {msg.phone}</p>
                </div>
              </div>

              <div className="flex items-center gap-3 text-xs">
                <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold border ${
                  msg.status === 'Resolved by AI' ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30' :
                  msg.status === 'Replied' ? 'bg-indigo-500/15 text-indigo-400 border-indigo-500/30' :
                  'bg-amber-500/15 text-amber-400 border-amber-500/30'
                }`}>
                  {msg.status}
                </span>
                <span className="text-slate-400 font-mono text-[11px]">{msg.timestamp}</span>
              </div>
            </div>

            {/* Content & Dialog preview */}
            <div className="space-y-2.5 text-xs">
              <div className="font-semibold text-indigo-300 flex items-center gap-1.5">
                <span>Subject:</span>
                <span className="text-white font-bold">{msg.subject}</span>
              </div>

              {/* Student message quote */}
              <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-slate-200">
                <strong className="text-slate-400 block text-[11px] mb-1">Student Question:</strong>
                <p className="leading-relaxed font-sans">{msg.lastMessage}</p>
              </div>

              {/* AI Auto Response if present */}
              {msg.aiResponse && (
                <div className="p-3 rounded-xl bg-indigo-950/30 border border-indigo-800/40 text-indigo-200">
                  <div className="flex items-center gap-1.5 text-indigo-400 font-bold text-[11px] mb-1">
                    <Bot className="w-3.5 h-3.5" />
                    <span>AdmitAI Auto-Response (Confidence: 98%):</span>
                  </div>
                  <p className="leading-relaxed">{msg.aiResponse}</p>
                </div>
              )}

              {/* Counselor Reply if already answered */}
              {msg.counselorReply && (
                <div className="p-3 rounded-xl bg-emerald-950/30 border border-emerald-800/40 text-emerald-200">
                  <div className="flex items-center gap-1.5 text-emerald-400 font-bold text-[11px] mb-1">
                    <ShieldCheck className="w-3.5 h-3.5" />
                    <span>Counselor Response ({msg.counselorName || 'Admissions Desk'}):</span>
                  </div>
                  <p className="leading-relaxed">{msg.counselorReply}</p>
                </div>
              )}
            </div>

            {/* Bottom Actions */}
            <div className="pt-3 mt-3 border-t border-slate-800/60 flex items-center justify-between">
              <span className="text-[11px] text-slate-400">Course Interest: <strong className="text-white">{msg.courseInterest}</strong></span>

              <button
                onClick={() => handleOpenReplyModal(msg)}
                className="px-3.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-sm transition-all flex items-center gap-1.5"
              >
                <span>{msg.counselorReply ? 'Update Counselor Reply' : 'Send Counselor Reply'}</span>
                <Send className="w-3 h-3" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* ============================================================
          COUNSELOR REPLY MODAL
      ============================================================ */}
      {selectedMessage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fadeIn">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-lg w-full p-6 shadow-2xl space-y-4 text-xs">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2 font-bold text-sm text-white">
                <Send className="w-4 h-4 text-indigo-400" />
                <span>Reply to {selectedMessage.studentName}</span>
              </div>
              <button
                onClick={() => setSelectedMessage(null)}
                className="text-slate-400 hover:text-white px-2 py-1 bg-slate-800 rounded-lg font-bold"
              >
                ✕
              </button>
            </div>

            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
              <span className="text-[11px] text-slate-400 block font-semibold">Student Inquiry:</span>
              <p className="text-slate-200">{selectedMessage.lastMessage}</p>
            </div>

            <form onSubmit={handleSendReply} className="space-y-3">
              <div className="space-y-1">
                <label className="text-[11px] text-slate-300 font-semibold">Counselor Name / Title</label>
                <input
                  type="text"
                  value={counselorName}
                  onChange={(e) => setCounselorName(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white outline-none focus:border-indigo-500"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] text-slate-300 font-semibold">Counselor Response Text</label>
                <textarea
                  rows={4}
                  value={replyText}
                  onChange={(e) => setReplyText(e.target.value)}
                  placeholder="Type official counseling guidance, fee confirmation, or document feedback..."
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs text-white placeholder-slate-500 outline-none focus:border-indigo-500"
                />
              </div>

              {replySuccess && (
                <div className="p-2.5 rounded-lg bg-emerald-500/15 border border-emerald-500/30 text-xs text-emerald-300 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Counselor response delivered to applicant's portal!</span>
                </div>
              )}

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setSelectedMessage(null)}
                  className="px-3.5 py-2 rounded-xl text-slate-400 hover:text-white bg-slate-800 font-medium"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={sending}
                  className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold shadow-md shadow-indigo-600/30 transition-all flex items-center gap-1.5"
                >
                  <span>{sending ? 'Sending...' : 'Send Official Response'}</span>
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
